### PR TITLE
tweaks: condensed bullets and indentation lines

### PR DESCRIPTION
**Pull request by runargs**
Added to the tweaks menu:
image

Condensed bullets:
image

Indentation lines:
image

Both!
image

### CODE REVIEW

**Comment by runargs** [comment]
It just occurred to me that it looks like autocorrect turns off when condense bullets is on. Any idea why?

**Comment by dragonwocky** [comment]
hm that's odd. i'll merge this and do some testing, see if I can figure it out. if you do find out what's going on just open a new PR.

**Comment by fourteen-1** [comment]
Shouldn't the lines be directly below the bullet points? Why are they off to the right side?

**Comment by runargs** [comment]
> Shouldn't the lines be directly below the bullet points? Why are they off to the right side?
> 
> ```
>  margin-left: -15px;
>   padding-left: 10px; 
> ```
> 
> This should do the trick.

Yeah, I ended up [implementing in after when someone mentioned it on Reddit](https://www.reddit.com/r/Notion/comments/jmuvq8/bullet_point_relationship_lines_similar_to_what/gb1dzxt?utm_source=share&utm_medium=web2x&context=1), I'll add it on in a new PR soon
image

**Comment by fourteen-1** [comment]
I'm curious, is it possible to implement relationship lines for Toggle Lists as well?

**Comment by runargs** [comment]
> I'm curious, is it possible to implement relationship lines for Toggle Lists as well?
Probably. I'll look into it when I have time, can you open an feature request issue?

**Pull request merged**
