### PR TITLE
Dracula Theme

### PR DESCRIPTION
**Pull request by mimi-shahzad**
A theme created based on the official Dracula Theme palette found https://draculatheme.com/contribute/. I do not own Dracula, but thought it would be nice to share this with others.

### CODE REVIEW

**Review by dragonwocky — CHANGES_REQUESTED** [review]
cool!

before merging, this needs a bit more to be an actual mod: to be registered/loaded it needs to be in a folder with a `mod.js` file [as specified in the documentation](https://github.com/dragonwocky/notion-enhancer/blob/master/DOCUMENTATION.md).

also, add `(c) 2020 Dracula Theme`  to the license list.

**Comment by dragonwocky** [comment]
I can squash it when I merge.

**Comment by mimi-shahzad** [comment]
awesome. I made the suggested changes, please let me know if anything else is needed. Thank you for your time. I am excited about this~

**Comment by mimi-shahzad** [comment]
oops, just added some changes, this should be the last of it. 😅

**Comment by mimi-shahzad** [comment]
oops please don't merge.. I tried to squash the commits but ended up doing something wrong

**Comment by mimi-shahzad** [comment]
New PR, sorry for the confusion https://github.com/dragonwocky/notion-enhancer/pull/142

**Pull request closed without merging**
