### PR TITLE
mods: add material ocean theme

### PR DESCRIPTION
**Pull request by Blacksuan19**
adds material ocean theme to built-in mods

### CODE REVIEW

**Review by dragonwocky — CHANGES_REQUESTED** [review]
I love material ocean! Before I merge:

- remove the centering of column headers / hiding of discussions / wider page preview etc. - themes should just be changing colour scheme, extra layout things like that are subject to user preference and so should be separate, either as tweaks with the custom-inserts mod or as their own extension.

- the colouring is extremely incomplete. please make ALL available colour variables match the material ocean palette.

**Comment by Blacksuan19** [comment]
Yeah I thought the same about the extra tweaks, will add the other colors and maybe make the extra tweaks in a separate mod

**Comment by dragonwocky** [comment]
@Blacksuan19 it might be better if instead of having a bunch of extensions for the tweaks, they were either all just in [TWEAKS.md](https://github.com/dragonwocky/notion-enhancer/blob/master/TWEAKS.md) or all in a single extension with options to toggle them on/off... so if you do end up moving these tweaks into a separate mod it'd be great if you could put all the available tweaks in that mod (excluding block-specific ones).

**Comment by Blacksuan19** [comment]
That's doable, will look into it

**Comment by Blacksuan19** [comment]
squashing and opening new completed request

**Pull request closed without merging**
