### PR TITLE
Fix linux installation

### PR DESCRIPTION
**Pull request by Blacksuan19**

### CODE REVIEW

**Comment by dragonwocky** [comment]
looks good... I'll check it out properly after school.
however, there actually wasn't actually "linux" support - that check for linux & windows at the same time was intentional, for the WSL.

i didn't know there was a linux app?

**Comment by Blacksuan19** [comment]
There is a Linux app and it's about the same as the windows version thanks to electron.
Am not sure if it's in other distros repositories but on arch Linux it's available from the AUR
https://aur.archlinux.org/packages/notion-app/

**Comment by dragonwocky** [comment]
Ah, looks like it's an unofficial build. There are a couple around - e.g. https://github.com/puneetsl/lotion, https://github.com/JosephDev/notion-linux-wrapper. I don't really have access to a Linux installation I can test a GUI app on at the moment... would you be able to give these all a go and find out which works best and relevant filepaths, etc.?

Also, what's the benefit of repacking the asar? It runs fine without, and I'm going with the idea that the "enhanced/customised" version should be kept easily identifiable as separate to the packed version Notion provides.

**Comment by Blacksuan19** [comment]
alright will test on these and report shortly

**Comment by Blacksuan19** [comment]
lotion installs itself in whatever directory it was cloned in so there is no way to determine its exact location, and the other one is a wrapper ie it just opens the site in a window and doesn't have any local resources.

so neither would work with this, I will try to locate lotion installation folder if that's possible

**Comment by Blacksuan19** [comment]
just found this: https://github.com/puneetsl/lotion/issues/31
lotion already has a way to inject CSS and js so I don't think I need to add support for it

**Comment by dragonwocky** [comment]
Right. Looks like their injection method is actually based off an old version of the enhancer, but yeah I'll leave it alone for now.

Before I merge, couple other things -

Can you revert [L32](https://github.com/dragonwocky/notion-enhancer/pull/4/commits/daf23478eaa9b478a6fde42b9a016e77c7a5e694#diff-e686bd31c153ba079fdb43858866080eR32): this will completely break it on windows, as it checks specifically for the WSL. As it checks there specifically for both Windows and Linux, changing that back won't interfere with Linux compatibility.

If you look at [L53](https://github.com/Blacksuan19/notion-enhancer/blob/master/customiser.py#L53), it checks for the presence of the `app` as a folder to handle things if the enhancer (presumably a previous version) is already applied. As-is, it will assume the modified and re-packaged app files are the original and cause all sorts of weird things. Any solutions?

I suggest:
```
if linux:
* extract
* check `filepath + '/app/ENHANCER_VERSION.txt'`
-- exists and version matches current enhancer_version = continue with enhancement
-- else: clean (remove folder + extract app.asar.bak. code for this should already be present,
   likely just needs to be refactored slightly)
```

**Comment by Blacksuan19** [comment]
the scripts current behavior always rewrites the backup, I just found the launch file and if pointed to app directory it launches the app without any issues, maybe the customizer could change app.asar to just app, this way no need to repack and the original app.asar always exists 

the line second to last is what needs to be changed to unify the behavior on Linux as well

image

**Comment by Blacksuan19** [comment]
ok I've modified the script to patch the launcher but that means the customizer has to be run as root, not a big deal if you ask me

**Comment by Blacksuan19** [comment]
I think it's ready now
- original app.asar is backed up and never replaced
- won't break other platforms
- updates should work just like on other platforms

**Comment by dragonwocky** [comment]
Awesome!

Before I merge README will need to be updated with details on Arch Linux app installation (as it's likely people will miss the Linux package since it's not on the website or get confused and think it applies to them when it doesn't).

Could you add that quick? It's probably just one command to install, but I don't have any experience with the AUR, so...

I've found something for Ubuntu too (https://github.com/jaredallard/notion-app), so giving that a test run now.

**Comment by Blacksuan19** [comment]
I'll update the readme shortly 
This repo is what the version in the AUR is based on, it works the same way by using macOS dmg

**Pull request merged**
